[package]
name = "guangzhou-metro"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
indexmap = { version = "2", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
